name: Deploy Spring Boot App to EC2 and Restart Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          passphrase: renta
          source: "target/Race-A-Car-0.0.1-SNAPSHOT.jar"
          target: "/var/myapp"
          distribution: "ubuntu"

      - name: SSH into EC2 and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          passphrase: renta
          script: |
            sudo systemctl stop myapp.service
            sudo systemctl start myapp.service

